version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: knex
      POSTGRES_USER: knex
    volumes:
      - PG_DB:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  PG_DB: